### ISSUE TITLE
Handle clipboard for Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by kenny-evitt** [kenny-evitt/password-store-buw#1]
See kenny-evitt/password-store#1 for prior details.

Tasks:

 - [x] Update *README*
 - [x] Finish writing and testing the `clip` function in the *linux.sh* Pass platform file.
 - [x] Test installing Pass from a local clone of this repo on your Windows computers.
 - [x] Investigate font settings changing when running `pass show -c ...` in BUW (on Leibniz).
 - [x] Cleanup 'WIP' commit in the topic branch for this issue.
 - [x] Merge commits into *master* branch.
 - [x] Email the Pass mailing list about this 'soft fork'.
 - [x] Submit a patch with the changes to the mailing list.
 - [x] Fix quoting bug.

**Comment by kenny-evitt** [comment]
Currently, the `clip` function (as-is in the topic branch for this issue) correctly writes the first parameter to the clipboard. And the 'clear' feature also seems to be working, except for it writing the first parameter, with a trailing newline, back to the clipboard instead of the original content of the clipboard.

Here's the current platform file:

```sh
# This file is actually for Bash on Ubuntu on Windows!

clip() {
    local sleep_argv0="password store sleep on display $DISPLAY"
    pkill -f "^$sleep_argv0" 2>/dev/null && sleep 0.5
    #local before="$(base64 < /dev/clipboard)"
    local before="$(read_from_clipboard | base64)"

    # TODO: Remove:
    echo "before: $(echo "$before" | base64 -d)"

    #echo -n "$1" > /dev/clipboard
    write_to_clipboard $(echo -n "$1")
    (
        ( exec -a "$sleep_argv0" sleep "$CLIP_TIME" )
        #local now="$(base64 < /dev/clipboard)"
        local now="$(read_from_clipboard | base64)"
        [[ $now != $(echo -n "$1" | base64) ]] && before="$now"
        #echo "$before" | base64 -d > /dev/clipboard
        write_to_clipboard $(echo "$before" | base64 -d)
    ) 2>/dev/null & disown
    echo "Copied $2 to clipboard. Will clear in $CLIP_TIME seconds."
}

read_from_clipboard() {
    /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -Command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Clipboard]::GetText()"
}

write_to_clipboard() {
    /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -Command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Clipboard]::SetText(\"$1\")"
}

# TODO: Remove:
CLIP_TIME=10
clip "abcd" "Test password"
```

This line seems to be not working as expected:

```
[[ $now != $(echo -n "$1" | base64) ]] && before="$now"
```

The test *should* be failing, not passing.

**Comment by kenny-evitt** [comment]
I'm just running the 'platform' script file directly to test this (from a Bash on Ubuntu on Windows window):

```bash
kenny@KEVITT-P3620:/mnt/d/@code/password-store-buw/src/platform$ ./linux.sh
before (base64): VGhpcyBzaG91bGQgYmUgb24gdGhlIGNsaXBib2FyZA0K
before: This should be on the clipboard
$1 (base64): YWJjZAo=
$1: abcd
$1 (base64): YWJjZAo=
$1: abcd
Copied Test password to clipboard. Will clear in 10 seconds.
kenny@KEVITT-P3620:/mnt/d/@code/password-store-buw/src/platform$ now (base64): YWJjZA0K
now: abcd
$1 (base64): YWJjZAo=
$1: abcd

```

Note that the value in `$now` is different than the original 'password', `$1`.

**Comment by kenny-evitt** [comment]
The problem I need to solve is that the output of the `read_from_clipboard` function includes trailing CRLF characters.

**Comment by kenny-evitt** [comment]
A LINQPad query 'program' I used to determine the differences between the various strings being read from or written to the clipboard:

```
void Main()
{
	"Original".Dump();
	"".Dump();
	DumpDecodedBytes(@"YWJjZAo=");

	"".Dump();
	"Read from clipboard".Dump();
	"".Dump();
	DumpDecodedBytes(@"YWJjZA0K");

	"".Dump();
	"Test clipboard text".Dump();
	"".Dump();
	DumpDecodedBytes(@"VGhpcyBzaG91bGQgYmUgb24gdGhlIGNsaXBib2FyZA0K");
}

// Define other methods and classes here

void DumpDecodedBytes(string base64EncodedData)
{
	byte[] base64EncodedBytes = System.Convert.FromBase64String(base64EncodedData);
	
	foreach (byte b in base64EncodedBytes)
	{
		b.Dump();
	}
}
```

Sample output:

> Original
> 
> 97
> 98
> 99
> 100
> 10
> 
> Read from clipboard
> 
> 97
> 98
> 99
> 100
> 13
> 10
> 
> Test clipboard text
> 
> 84
> 104
> 105
> 115
> 32
> 115
> 104
> 111
> 117
> 108
> 100
> 32
> 98
> 101
> 32
> 111
> 110
> 32
> 116
> 104
> 101
> 32
> 99
> 108
> 105
> 112
> 98
> 111
> 97
> 114
> 100
> 13
> 10

**Comment by kenny-evitt** [comment]
I think I've got the functions in the platform script finally working.

I'm going to test installing the new version by running `make install` from the repo root directory in a BUW window.

[I've been working on my computer at work so far today.]

**Comment by kenny-evitt** [comment]
```bash
kenny@KEVITT-P3620:/mnt/d/@code/password-store-buw$ make install
install: cannot remove '/usr/share/man/man1/pass.1': Permission denied
Makefile:38: recipe for target 'install-common' failed
make: *** [install-common] Error 1
kenny@KEVITT-P3620:/mnt/d/@code/password-store-buw$ sudo make install
[sudo] password for kenny:
removed '/usr/share/man/man1/pass.1'
'man/pass.1' -> '/usr/share/man/man1/pass.1'
removed '/usr/share/bash-completion/completions/pass'
'src/completion/pass.bash-completion' -> '/usr/share/bash-completion/completions/pass'
'src/platform/linux.sh' -> '/usr/lib/password-store/platform.sh'
removed '/usr/bin/pass'
'src/.pass' -> '/usr/bin/pass'
```

**Comment by kenny-evitt** [comment]
And it worked! `pass show -c ...` copied the relevant password to the clipboard and I was able to login to a website by using <kbd>Ctrl</kbd>+<kbd>c</kbd> to paste the password in the website password input box.

**Comment by kenny-evitt** [comment]
I cloned the repo (and checked-out the topic branch for this issue) onto Leibniz and ran `sudo make install` from the repo root directory in a BUW window.

I was able to use `pass show -c ...` to copy a password. But the font for the text in the BUW window changed, to a bold or larger version of the original font setting. I want to look into that.

**Comment by kenny-evitt** [comment]
I was able to reproduce the font-settings changes in a new BUW window on Leibniz.

**Comment by kenny-evitt** [comment]
I'm going to ignore the 'font-settings changes' thing.

**Comment by kenny-evitt** [comment]
Jason (the Pass author and maintainer) asked me to submit a patch with the changes.

**Comment by kenny-evitt** [comment]
I replied to Jason's email on the mailing list and included a patch with the changes.

**Comment by kenny-evitt** [comment]
Bug, from L:

```bash
me@computer:~$ pass show -c password
At line:1 char:95
+ ... dows.Forms; [System.Windows.Forms.Clipboard]::SetText("this is not" ...
+                                                                       ~
Missing ')' in method call.
At line:1 char:106
+ ... Windows.Forms.Clipboard]::SetText("this is not" my password")
+                                                         ~~~~~~~~~~~~~~~~~
The string is missing the terminator: '.
At line:1 char:95
+ ... Windows.Forms.Clipboard]::SetText("this is not" my password")
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token ' my password' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

Copied password to clipboard. Will clear in 45 seconds.
```

This is a bad error; an apparent password, from the clipboard, is being leaked to the terminal. I need to:

 - [x] Review code handling the contents of the clipboard and ensure its data isn't leaked, e.g. to the terminal standard output. Maybe I can't really do this tho (beyond just fixing the obvious bugs).

 - [x] Quote the clipboard contents correctly, i.e. by escaping double quote characters.

**Comment by kenny-evitt** [comment]
I just ran into the quoting bug on my work computer:

```bash
me@computer:~$ pass show -c password
At line:1 char:95
+ ... dows.Forms; [System.Windows.Forms.Clipboard]::SetText("this is not" ...
+                                                                       ~
Missing ')' in method call.
At line:1 char:106
+ ... Windows.Forms.Clipboard]::SetText("~~~~~")
+                                                       ~~~~~~~~~~~~
The string is missing the terminator: '.
At line:1 char:95
+ ... Windows.Forms.Clipboard]::SetText("this is not" my' password")
+                                                    ~~~~~~~~~~~~~~~
Unexpected token  '" my' password")' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

Copied password to clipboard. Will clear in 45 seconds.
```

**Comment by kenny-evitt** [comment]
I generated a new patch `git format-patch HEAD^`. I'm going to email the Pass mailing list thread and include it.

**Comment by kenny-evitt** [comment]
I emailed the mailing list and included the new patch.

**Comment by kenny-evitt** [comment]
I'm getting the same quoting error on L again.

**Comment by kenny-evitt** [comment]
I wasn't running the latest code. I cleaned-up *master* and deleted *issue1*, in GitHub too.
